int getGridSize(int);
void genGrid(float *, int);
int getCubeSize();
float *genCube();
int getCircleSize(int);
void genCircle(float *, int);
int getSphereSize(int, int);
void genSphere(float *, int, int);
int getTorusSize(int, int);
void genTorus(float *, int, int, float);
